// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package getters

import (
	"github.com/tokend/stellar-deposit-svc/internal/horizon"
	"github.com/tokend/stellar-deposit-svc/internal/horizon/query"
	logan "gitlab.com/distributed_lab/logan/v3"
	"gitlab.com/distributed_lab/logan/v3/errors"
	regources "gitlab.com/tokend/regources/generated"
)

type AssetGetter struct {
	horizon.Interface
}

func (g *AssetGetter) AssetByID(ID string, params query.AssetParams) (*regources.AssetResponse, error) {
	result := &regources.AssetResponse{}
	err := g.GetSingle(query.AssetByID(ID), params, result)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get record by id", logan.F{
			"id": ID,
		})
	}

	return result, nil
}

func (g *AssetGetter) AssetList(params query.Params) (*regources.AssetListResponse, error) {
	result := &regources.AssetListResponse{}
	err := g.GetList(query.AssetList(), params, result)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get records list", logan.F{
			"query_params": params,
		})
	}

	return result, nil
}

func (g *AssetGetter) Next(links *regources.Links) (*regources.AssetListResponse, error) {
	if links == nil {
		return nil, errors.New("Empty links")
	}
	result := &regources.AssetListResponse{}
	err := g.PageFromLink(links.Next, result)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get next page", logan.F{
			"link": links.Next,
		})
	}

	return result, nil
}
